### ISSUE TITLE
Problem installing node

### ISSUE THREAD

**Issue by sohaib19922** [FizzleDorf/ComfyUI_FizzNodes#110]
Hi, what is the solution to the problem? (IMPORT FAILED) FizzNodes
![screenshot 133707231826454073](https://github.com/user-attachments/assets/1c73d656-96b2-469a-9fa2-7c1fb06e2695)

**Comment by FizzleDorf** [comment]
I am about to head to bed but I need you to post the full traceback in the terminal after the install fails and I can look into it tomorrow

**Comment by FizzleDorf** [comment]
Just want to remind you that I can't know how to solve the problem until the trace is posted here. The info you gave me is too ambiguous for me to help in a meaningful way.

**Comment by sohaib19922** [comment]
شكرا لك هل تقصد ملف العمل الذي أعمل عليه  ؟ 
[workflow-template-for-prompt-travel-openpose-controlnet-kYKv5sJWchSsujm0zOV0-matt3o-openart.ai.json](https://github.com/user-attachments/files/17000943/workflow-template-for-prompt-travel-openpose-controlnet-kYKv5sJWchSsujm0zOV0-matt3o-openart.ai.json)

**Comment by FizzleDorf** [comment]
no I meant the error traceback in the terminal (the black window that launches the server). try reinstalling again then copy and paste from where it says "traceback" all the way until the end.

**Comment by Cometakah** [comment]
Well, taking advantage of the fact that the bro never answered, i will send what appears to me.

![image](https://github.com/user-attachments/assets/fd1f66cb-df57-4c2e-9489-845caf713b15)

```
Cannot import C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes module for custom nodes: Unable to import required dependencies:
pytz: No module named 'pytz'
dateutil: No module named 'dateutil'
```

I have the portable version of ComfyUI installed, maybe that is the problem. However, I tried inside the ComfyUI folder to run the command:

❌ `pip install pytz` ❌

and it was installed but apparently it was in vain because it still shows me that it is not installed.

The other "dateutil" i tried to do the same:

❌ `pip install dateutil` ❌

but only in this case, i got: 

```
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement dateutil (from versions: none)
ERROR: No matching distribution found for dateutil
```

Anyway I have a problem with ComfyUI since it asks me for the same "dateutil" module, so I'm going to try to fix that first and come back to this GITHUB in case the problem was with the installation of ComfyUI portable and its extension ComfyUI manager (Since possibly the ComfyUI portable error is going to FizzNodes).

Possibly the guy or whoever is reading this has had the same problem as me, so I'll try to provide as much information as possible. I'm attaching data about the error that I get in ComfyUI but it's not for spam or anything, it's just for people to compare if it's the same problem or not <3 (Thanks for reading and for your time)

```
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Traceback (most recent call last):
  File "C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TRA\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TRA\nodes.py", line 5, in <module>
    from .tcl_yolov8 import TclYoloV8Segmentation
  File "C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TRA\tcl_yolov8.py", line 1, in <module>
    from ultralytics import YOLO
  File "C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\__init__.py", line 11, in <module>
    from ultralytics.models import NAS, RTDETR, SAM, YOLO, FastSAM, YOLOWorld
  File "C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
    from .fastsam import FastSAM
  File "C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\fastsam\__init__.py", line 3, in <module>
    from .model import FastSAM
  File "C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\fastsam\model.py", line 5, in <module>
    from ultralytics.engine.model import Model
  File "C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\engine\model.py", line 11, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\cfg\__init__.py", line 10, in <module>
    from ultralytics.utils import (
  File "C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\utils\__init__.py", line 23, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\python_embeded\Lib\site-packages\matplotlib\__init__.py", line 263, in <module>
    _check_versions()
  File "C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\python_embeded\Lib\site-packages\matplotlib\__init__.py", line 257, in _check_versions
    module = importlib.import_module(modname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 90, in import_module
ModuleNotFoundError: No module named 'dateutil'

Cannot import C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TRA module for custom nodes: No module named 'dateutil'
Traceback (most recent call last):
  File "C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\__init__.py", line 57, in <module>
    from .ScheduledNodes import (
  File "C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 7, in <module>
    import pandas as pd
  File "C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pandas\__init__.py", line 32, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
pytz: No module named 'pytz'
dateutil: No module named 'dateutil'

Cannot import C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes module for custom nodes: Unable to import required dependencies:
pytz: No module named 'pytz'
dateutil: No module named 'dateutil'

Import times for custom nodes:
   0.0 seconds: C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.0 seconds: C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.1 seconds: C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.2 seconds (IMPORT FAILED): C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TRA
   0.3 seconds: C:\Users\Cometakah\Documents\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server
```

**Comment by Cometakah** [comment]
**OMG I FIX IT!!! XD**

![image](https://github.com/user-attachments/assets/c817fa27-8d24-4a16-aad3-be8bff23aa70)

**The problem is with the Python from ComfyUI Portable called "python_embeded".
ComfyUI Manager installs the packages in the local Python, not the Python that comes with ComfyUI local.**

For fix it, you need to go to the folder where "python_embeded" is:

![image](https://github.com/user-attachments/assets/9ba9d44a-6d33-4364-8157-ade2ccf7ad66)

Type "cmd" in the explorer browser:

![image](https://github.com/user-attachments/assets/77d0411f-8e21-4f05-97a6-ae6052116c35)

and here:

![image](https://github.com/user-attachments/assets/a2cf53ec-af7b-4e18-af34-f1892bb2df83)

enter the following command for fix pytz:

```
.\python_embeded\python.exe -m pip install pytz --force-reinstall
```

and the next command for fix dateutil: 

```
.\python_embeded\python.exe -m pip install python-dateutil --force-reinstall
```

In case there are problems with modules in ComfyUI, you have to run the command ".\python_embeded\python.exe -m" before "pip" to install it in the ComfyUI portable Python. This way any missing modules can be resolved.

".\python_embeded\python.exe -m pip install **_(Your module missing)_** --force-reinstall"

(Sorry for my bad English, I'm from Chile, so if i speak something wrong, please tell me and I will correct it so that whoever with the problem can solve it. If you ask why the explanation is so detailed, it is because, not being an English speaker and being stupid, it is twice as difficult for me to understand this type of things, so it is a help for anyone who finds it complicated. Sorry for the long text, have a nice day <3)

**Comment by FizzleDorf** [comment]
No worries. Thanks for detailing the traceback and fix! This will be helpful for anyone else having the same issue.

**Comment by afffsrsgd** [comment]
not working for me 

> No worries. Thanks for detailing the traceback and fix! This will be helpful for anyone else having the same issue.

not working for me

**Comment by Cometakah** [comment]
> not working for me
> 
> > No worries. Thanks for detailing the traceback and fix! This will be helpful for anyone else having the same issue.
> 
> not working for me

What Error do you get in your CMD?

**Comment by lazwardi** [comment]
i have the same problem, but in my terminal it says:

`ModuleNotFoundError: No module named 'numexpr'`

but i already had installed numexpr on my 'phyton_embedded' env.

```
PS D:\Apps\ComfyUI\python_embeded> .\python.exe -m pip show numexpr
Name: numexpr
Version: 2.8.7
Summary: Fast numerical expression evaluator for NumPy
Home-page: https://github.com/pydata/numexpr
Author: David M. Cooke, Francesc Alted, and others
Author-email:
License: MIT
Location: D:\Apps\ComfyUI\python_embeded\Lib\site-packages
Requires: numpy
Required-by:
PS D:\Apps\ComfyUI\python_embeded>
```

this is part from the terminal:
```
Traceback (most recent call last):
  File "D:\Apps\ComfyUI\ComfyUI\nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Apps\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes\__init__.py", line 57, in <module>
    from .ScheduledNodes import (
  File "D:\Apps\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 4, in <module>
    import numexpr
ModuleNotFoundError: No module named 'numexpr'

Cannot import D:\Apps\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes module for custom nodes: No module named 'numexpr'
```

I have Python 3.11.6 in my 'python_embeded'

**Comment by Cometakah** [comment]
> i have the same problem, but in my terminal it says:
> 
> `ModuleNotFoundError: No module named 'numexpr'`
> 
> but i already had installed numexpr on my 'phyton_embedded' env.
> 

You should try:

`.\python_embeded\python.exe -m pip install numpy --force-reinstall`

It seems that this is the missing module.


/////////////////////////////////////////////////////////////////////////////////////////////////////


**_In case that doesn't work:_**

Sometimes there are multiple versions of Python on Windows, it could happen that by mistake maybe the program is running in a different version than the ComfyUI Python Environment....

You should locate your other Python310 environments and run the "pip install" command in them like this:

`C:\Program Files\Python310\python.exe -m pip install ((NAME OF YOUR MISSING MODULE)) --force-reinstall
`

In this case I did it on my folder of Phyton 3.10.... But you should change the first part of the code:

`C:\Program Files\Python310\...` 

Keeping the part of: `python.exe -m pip install ((NAME OF YOUR MISSING MODULE)) --force-reinstall` in the end

For example if it is in Python Python 3.12, find the Python folder with that version number...
_(In case you have customized it, look for where you installed it by searching for Python in the Windows search engine, right click and open the file location. In case a shortcut appears, do that again and you will enter the folder.)
(Make sure there aren't any other ones and if there are, do the procedure on them too.)_
...and copying the address, paste it into a CMD console and paste the remaining code, it should look something like this:
 
`D:\MyPythons\CustomInstall\Python312\python.exe -m pip install numpy --force-reinstall
`
_(It's just an example, so don't copy and paste, as it has folders created as an example.)_

**You should try that, Hope it works buddy! 😊 (Sorry for the delay in response)**


/////////////////////////////////////////////////////////////////////////////////////////////////////


_PD: Why " --force-reinstall" command?
Because sometimes it is installed incorrectly, it cannot be run and it is possible that when you try to install it, it will tell you that it is finished. So with the command " --force-reinstall" you force everything to be deleted in order to do it again._
