### ISSUE TITLE
ComfyUI_FizzNodes module for custom nodes: No module named 'numexpr.interpreter

### ISSUE THREAD

**Issue by ZTWY35** [FizzleDorf/ComfyUI_FizzNodes#20]
Traceback (most recent call last):
  File "D:\Program Files\ComfyUI_10\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Program Files\ComfyUI_10\ComfyUI\custom_nodes\ComfyUI_FizzNodes\__init__.py", line 57, in <module>
    from .ScheduledNodes import ValueSchedule, PromptSchedule, PromptScheduleNodeFlow, PromptScheduleNodeFlowEnd, PromptScheduleEncodeSDXL, StringSchedule, BatchPromptSchedule, BatchValueSchedule, BatchPromptScheduleEncodeSDXL #, BatchGLIGENSchedule
  File "D:\Program Files\ComfyUI_10\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 4, in <module>
    import numexpr
  File "D:\Program Files\ComfyUI_10\python_embeded\lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__
ModuleNotFoundError: No module named 'numexpr.interpreter'

Cannot import D:\Program Files\ComfyUI_10\ComfyUI\custom_nodes\ComfyUI_FizzNodes module for custom nodes: No module named 'numexpr.interpreter'

**Comment by Laayer-1** [comment]
Traceback (most recent call last):
  File "C:\Blender_ComfyUI\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes\__init__.py", line 57, in <module>
    from .ScheduledNodes import ValueSchedule, PromptSchedule, PromptScheduleNodeFlow, PromptScheduleNodeFlowEnd, PromptScheduleEncodeSDXL, StringSchedule, BatchPromptSchedule, BatchValueSchedule, BatchPromptScheduleEncodeSDXL #, BatchGLIGENSchedule
  File "C:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 4, in <module>
    import numexpr
ModuleNotFoundError: No module named 'numexpr'

Cannot import C:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes module for custom nodes: No module named 'numexpr'

**Comment by FizzleDorf** [comment]
Try installing numexpr: `Pip install numexpr` or `.\python_embed\python.exe -s -m` . It seems it isn't being installed from the requirements and I might have to try something else to get it installed properly. Let me know if this solves the issue.

**Comment by DanielWGAnimateDiff** [comment]
I also encountered the same problem, using the command you gave, no, it failed, because comfyUI uses its own python, and this built-in python when executing Install, it will report some exceptions that cannot create a file under disk D. This looks like the first directory where comfyUI python was deployed,It looks a bit like the directory on the computer of the first person who deployed comfyUI python himself

**Comment by DanielWGAnimateDiff** [comment]
I think this problem probably bothers most people who want to try this plugin, authors, Can you compress your local numexpr directory and upload it to github so that everyone can download and decompress it directly into the local $ComfyUI_HOME\python_embeded\Lib\site-packages directory? And make sure your local comfyUI python version is 3.11.6

**Comment by kingzhongmu** [comment]
> I think this problem probably bothers most people who want to try this plugin, authors, Can you compress your local numexpr directory and upload it to github so that everyone can download and decompress it directly into the local $ComfyUI_HOME\python_embeded\Lib\site-packages directory? And make sure your local comfyUI python version is 3.11.6

I have solved it by copying   'numexpr' files  to the path  $ComfyUI_HOME\python_embeded\Lib\site-packages
