### ISSUE TITLE
BatchPromptSchedule "RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 77 but got size 154 for tensor number 3 in the list."

### ISSUE THREAD

**Issue by gavinliukaiber** [FizzleDorf/ComfyUI_FizzNodes#28]
I am using the latest commit. And the error in the title is at this [line](https://github.com/FizzleDorf/ComfyUI_FizzNodes/blob/511ebe532b5a545a2169a49064c7be7df0ac3c19/BatchFuncs.py#L168).

It seems the introduction of `group_size = 4` in this [commit](https://github.com/FizzleDorf/ComfyUI_FizzNodes/commit/8b84f463ad8ae9ee180a222604bc00d44fca99e3) is causing this bug. 

Here's the input to illustrate the bug:

```
"0" :"a girl",

"15" :"female, Russian Gopnik, sport jacket, tracksuit, background symbol graffiti, ruined city, concrete, portrait, long red hair, human thoughts art, elegant fantasy, intricate, crisp quality, Bela Magyar, 35mm film, 35mm photography, 8k uhd, hdr, ultra-detailed, Wet black and orange color inks line art dreamy female portrait with lot of lace filigrees on black canvas illustration described in the perfect fractal (style of Vassily Kandinsky)",

"35" :"a girl"
```

Before timestamp 15, clip returns `torch.Size([1, 77, 768])` , and then it returns `torch.Size([1, 154, 768])`, and hence triggered the bug. I wonder why  this [commit](https://github.com/FizzleDorf/ComfyUI_FizzNodes/commit/8b84f463ad8ae9ee180a222604bc00d44fca99e3) is necessary? It says "VRAM usage improved", but this "optimization" doesn't reduce the total number of tensors stored in VRAM, which is still equal to `max_frame`. Should we remove this to fix the bug?

**Comment by gavinliukaiber** [comment]
Hmm, a separate question: I can see that with `group_size = 4`, BatchPromptSchedule's output shape becomes `torch.Size([4, max_frame/4, 768])` , and somehow the VRAM usage during KSampler significantly dropped. Why does this happen? (I have AnimateDiff in the workflow) Any docs/code points would be much appreciated.

**Comment by FizzleDorf** [comment]
right on. I made the fix and everything is fine. The fix is in 36ff6a7

**Comment by gavinliukaiber** [comment]
Hmm, but I git pulled, and tried the input in my original post, and I still get the same error at line 195, in BatchPoolAnimConditioning
    final_conditioning = torch.cat(cond_out, dim=0)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 77 but got size 154 for tensor number 15 in the list.

Still seems like a  padding issue... I wonder if we can fix this by somehow make CLIP return 157 tokens for the first 15 timestamps?

**Comment by whitehumorous85** [comment]
I am having the same issue. When the length of the prompt of each keyframe different too much will trigger this error.

**Comment by FizzleDorf** [comment]
I am getting reports this is still an issue which is odd because I haven't been proccing this error. This may have to do with using older workflows and the updated nodes still show the same behavior as before. I asked someone to test using "fresh" nodes and copying over the parameters to see if this solves the issue. I am not able to test for most of the day at work unfortunately.

**Comment by Slowly-Grokking** [comment]
what triggers it for me is trying to use 'embedding:some.pt' anywhere except for the first prompt.
i tried using the append field, as well as manually putting the embedding in prompts.

`  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 125, in animate
    pc = BatchPoolAnimConditioning( pos_cur_prompt, pos_nxt_prompt, weight, clip,)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\BatchFuncs.py", line 207, in BatchPoolAnimConditioning
    final_conditioning = torch.cat(cond_out, dim=0)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 77 but got size 154 for tensor number 30 in the list.`

**Comment by Zanerkin** [comment]
I've been encountering this error on a fresh install of ComfyUi and FizzNodes with a newly created workflow:
 `Error occurred when executing BatchPromptSchedule:

Sizes of tensors must match except in dimension 0. Expected size 154 but got size 77 for tensor number 336 in the list.`

As a workaround I've been padding my keyframe prompts with something like "Highly Detailed, Highly Detailed, Highly Detailed", so that they all end up 154 size. Hardly an elegant solution but seems to get the job done.

**Comment by FizzleDorf** [comment]
try the latest commit that fixes this `d9f532a`

**Comment by NullEqualsZero** [comment]
I am having the same issue 
fresh workflow and all new instal of the node and I get the following error
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
missing {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
[AnimateDiffEvo] - INFO - Loading motion module mm_sd_v15_v2.safetensors
D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\BatchFuncs.py:128: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  cur_prompt_series[f] = ''
D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\BatchFuncs.py:129: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  nxt_prompt_series[f] = ''
Requested to load SD1ClipModel
Loading 1 new model
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 125, in animate
    pc = BatchPoolAnimConditioning( pos_cur_prompt, pos_nxt_prompt, weight, clip,)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\BatchFuncs.py", line 218, in BatchPoolAnimConditioning
    final_conditioning = torch.cat(cond_out, dim=0)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 77 but got size 154 for tensor number 26 in the list.

Prompt executed in 128.58 seconds

**Comment by whitehumorous85** [comment]
> I've been encountering this error on a fresh install of ComfyUi and FizzNodes with a newly created workflow: `Error occurred when executing BatchPromptSchedule:
> 
> Sizes of tensors must match except in dimension 0. Expected size 154 but got size 77 for tensor number 336 in the list.`
> 
> As a workaround I've been padding my keyframe prompts with something like "Highly Detailed, Highly Detailed, Highly Detailed", so that they all end up 154 size. Hardly an elegant solution but seems to get the job done.

Hi, do you manage to solve the issue using the latest commit without purposely adding unnecessary prompt? I updated to the latest one but is still having the same issue.

**Comment by FizzleDorf** [comment]
when you updated, did you restart the back-end and refresh the page?
