### ISSUE TITLE
Cannot import E:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes module for custom nodes: No module named 'pandas._libs.pandas_parser'

### ISSUE THREAD

**Issue by NOeSIS-yu** [FizzleDorf/ComfyUI_FizzNodes#41]
Traceback (most recent call last):
  File "E:\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\__init__.py", line 57, in <module>
    from .ScheduledNodes import (
  File "E:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 7, in <module>
    import pandas as pd
  File "E:\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\pandas\__init__.py", line 59, in <module>
    from pandas.core.api import (
  File "E:\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\pandas\core\api.py", line 1, in <module>
    from pandas._libs import (
  File "E:\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\pandas\_libs\__init__.py", line 16, in <module>
    import pandas._libs.pandas_parser  # noqa: E501 # isort: skip # type: ignore[reportUnusedImport]
ModuleNotFoundError: No module named 'pandas._libs.pandas_parser'

Cannot import E:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes module for custom nodes: No module named 'pandas._libs.pandas_parser'

**Comment by FizzleDorf** [comment]
try installing pandas manually.
start with: `pip uninstall pandas`
then : `pip install pandas`
make sure your virtual environment is activated before doing this

**Comment by quantass** [comment]
Actually the solution for me (on Windows) was to navigate to the Pyton site_packages folder
C:\Users\<user_name>\appdata\local\programs\python\python310\lib\site-packages\

Then to copy the appropriate package name (ie. Pandas, and other matching names) to the ComfyUI equivalent folder:
E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\

Restart and checked the terminal for more errors. I kept doing this for all the missing modules.  Everything worked after that.

**Comment by FizzleDorf** [comment]
nice, glad the issue was resolved. It's been a tricky installation with numexpr and pandas libraries. the former because it is sometimes skipped in the requirements pip install and the latter because it misses some things in the library. I hope you have fun with these nodes!
