### ISSUE TITLE
BatchPromptSchedule missing

### ISSUE THREAD

**Issue by Roguefromearth** [FizzleDorf/ComfyUI_FizzNodes#47]
Hi,

I have redownloaded it several times with comfyui manager and manually both but it keeps on showing this error. I have also reinstalled and checked everything from requirements.txt. 

Need Help! 

Thanks,

![Screenshot 2023-12-08 120135](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/139007697/ebdd8f86-bd4d-45d3-8a75-8eb48c3ea660)

**Comment by Roguefromearth** [comment]
Yes,


E:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py
--windows-standalone-build
Failed to execute startup-script:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py
/ source code string cannot contain null bytes

Prestartup times for custom nodes:
   0.0 seconds:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds (PRESTARTUP FAILED):
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 65450 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Impact-Pack (V4.38.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3.2)
[WARN] ComfyUI-Impact-Pack: `ComfyUI` or `ComfyUI-Manager` is an outdated
version.
### Loading: ComfyUI-Manager (V1.5.2)
### ComfyUI Revision: 1795 [a4ec54a4] | Released on '2023-12-08'
Comfyroll Custom Nodes: Loaded
[comfyui_controlnet_aux] | INFO -> Using ckpts path:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers:
['CUDAExecutionProvider', 'DirectMLExecutionProvider',
'OpenVINOExecutionProvider', 'ROCMExecutionProvider',
'CPUExecutionProvider']
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:25:
UserWarning: DWPose: Onnxruntime not found or doesn't come with
acceleration providers, switch to OpenCV with CPU device. DWPose might run
very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with
acceleration providers, switch to OpenCV with CPU device. DWPose might run
very slowly")
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in
load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in
_call_with_frames_removed
  File
"E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\__init__.py",
line 57, in <module>
    from .ScheduledNodes import (
  File
"E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py",
line 4, in <module>
    import numexpr
ModuleNotFoundError: No module named 'numexpr'

Cannot import
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes module
for custom nodes: No module named 'numexpr'
[tinyterraNodes] Loaded
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix
Script' Node (comfyui_controlnet_aux add-on)...Success!
Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node
(ComfyUI-AnimateDiff-Evolved add-on)...Success!
Efficiency Nodes Warning: Failed to import python package 'simpleeval';
related nodes disabled.


[rgthree] Loaded 18 exciting nodes.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or
re-queueing seems broken, change "patch_recursive_execution" to false in
rgthree_config.json

Searge-SDXL v4.3.1 in
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in
load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in
_call_with_frames_removed
  File
"E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\__init__.py",
line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File
"E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py",
line 36, in <module>
    from numba import jit
ModuleNotFoundError: No module named 'numba'

Cannot import
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
module for custom nodes: No module named 'numba'

Import times for custom nodes:
   0.0 seconds:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SD-Latent-Upscaler
   0.0 seconds:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-previewlatent
   0.0 seconds:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds (IMPORT FAILED):
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.0 seconds:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds (IMPORT FAILED):
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   0.1 seconds:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.3 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
   0.3 seconds:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.8 seconds:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from:
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
