### ISSUE TITLE
No idea of the fix

### ISSUE THREAD

**Issue by Cedri4** [FizzleDorf/ComfyUI_FizzNodes#54]
Terminal error 
"
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 77, in animate
    animation_prompts = json.loads(inputText.strip())
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 35 (char 34)
"
![image](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/93396286/420c0513-9fe2-4305-9566-24bc2fe513fa)

**Comment by Cedri4** [comment]
I also tried without the math function but it also doesn't works

**Comment by FizzleDorf** [comment]
The batch string schedule puts out a raw list of the scheduled prompts but not the dictionary values. so your prompt example would be sending:
`
(neutral:weight calc at frame #),
(neutral:weight calc at frame #),
(neutral:weight calc at frame #),
(neutral:weight calc at frame #),
(neutral:weight calc at frame #),
(hint_of_smile:weight calc at frame #),
(hint_of_smile:weight calc at frame #),
(hint_of_smile:weight calc at frame #),
etc.
`
some repos use lists of prompts for their inputs but the prompt schedules in this repo need to be formatted to the dictionary format like in the examples. the regular string schedule is the same but only outputs the one prompt at the current frame, not the dictionary value. to do what I think you want to do, use a primitive as the input. the values are still calculated by the regular prompt schedule nodes. I hope this helps!
