### ISSUE TITLE
BatchFuncs.py error when enable 'print_output'

### ISSUE THREAD

**Issue by hinablue** [FizzleDorf/ComfyUI_FizzNodes#56]
```
services-comfy-1  | ERROR:root:Traceback (most recent call last):
services-comfy-1  |   File "/app/execution.py", line 154, in recursive_execute
services-comfy-1  |     output_data, output_ui = get_output_data(obj, input_data_all)
services-comfy-1  |   File "/app/execution.py", line 84, in get_output_data
services-comfy-1  |     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
services-comfy-1  |   File "/app/execution.py", line 77, in map_node_over_list
services-comfy-1  |     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
services-comfy-1  |   File "/app/custom_nodes/ComfyUI_FizzNodes/ScheduledNodes.py", line 300, in animate
services-comfy-1  |     return (BatchInterpolatePromptsSDXL(animation_promptsG, animation_promptsL, max_frames, clip,  app_text_G, app_text_L, pre_text_G, pre_text_L, pw_a, pw_b, pw_c, pw_d, width, height, crop_w, crop_h, target_width, target_height, print_output,),)
services-comfy-1  |   File "/app/custom_nodes/ComfyUI_FizzNodes/BatchFuncs.py", line 438, in BatchInterpolatePromptsSDXL
services-comfy-1  |     for i in range(len(cur_prompt_series)):
services-comfy-1  | NameError: name 'cur_prompt_series' is not defined. Did you mean: 'cur_prompt_series_G'?
```

Typo in ComfyUI_FizzNodes/BatchFuncs.py line 438?
https://github.com/FizzleDorf/ComfyUI_FizzNodes/blame/5458adafb7cb42a6b194d1ac47a07a7af98f1957/BatchFuncs.py#L438

**Comment by Paero** [comment]
I experienced the same error and I created a pull request with a fix, which should also fix some other problems.

**Comment by FizzleDorf** [comment]
thanks for the PR! It's been super busy for me in the past while but I'll be doing some work on the repo this week. As for this issue, the PR has been merged already so I will be closing this.
