### ISSUE TITLE
After the update it becomes： NameError: name 'latents' is not defined

### ISSUE THREAD

**Issue by axdwct** [FizzleDorf/ComfyUI_FizzNodes#86]
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\ProgramData\anaconda3\envs\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\ProgramData\anaconda3\envs\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\ProgramData\anaconda3\envs\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 150, in animate
    return batch_prompt_schedule(settings, clip)
  File "C:\ProgramData\anaconda3\envs\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduleTypes.py", line 60, in batch_prompt_schedule
    return (p, n, latents,)
NameError: name 'latents' is not defined

**Comment by Djanghost** [comment]
Same here

**Comment by tarunrishi** [comment]
Same here

**Comment by FizzleDorf** [comment]
apologies everyone. I missed the extra return variable late last night. I applied a hotfix so everything will be ok if you pull. thanks for letting me know!
